# Generated by Django 3.2.3 on 2021-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mails',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mails',
            name='receiver',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
